
version: 2

models:
  - name: fivetran_test
    description: "A starter dbt model"
    columns:
      - name: decision
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

